title: seize the dev

author: Mohamed Akram
email: mohd.akram@outlook.com

social:
  github: mohd-akram
  twitter: tixilite

disqus:
  shortname: mohd-akram

google_analytics: UA-40999116-1

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /posts/:title

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      author: Mohamed Akram
