title: seize the dev

url: https://akr.am

author:
  name: Mohamed Akram
  email: mohd.akram@outlook.com

social:
  website: akr.am

disqus:
  shortname: mohd-akram

google_analytics: UA-40999116-1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  math_engine: katex
  math_engine_opts:
    output: mathml

permalink: /posts/:title

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Mohamed Akram
